"""
Request and Response schemas for the FastAPI agent endpoints.

Pydantic validates all inbound data before it touches the agent.
This is the contract between Django (caller) and FastAPI (agent runner).
"""
from typing import Optional, List
from pydantic import BaseModel, Field


class AgentRunRequest(BaseModel):
    """
    Payload Django sends to FastAPI to start an agent run.

    The resume PDF is base64-encoded so it can travel as JSON.
    A typical resume PDF is 100–500 KB, so encoded it's 133–665 KB —
    acceptable for local container-to-container communication.
    """
    run_id: str = Field(description="UUID generated by Django before calling FastAPI")
    user_id: str = Field(description="Django User UUID string")
    application_id: str = Field(description="Django Application UUID string")
    jd_raw: str = Field(description="Full job description text")
    jd_url: Optional[str] = Field(default=None, description="Optional job posting URL")
    resume_pdf_base64: str = Field(description="Base64-encoded PDF bytes")
    resume_raw_text: str = Field(
        default="",
        description="Pre-extracted resume text from Django upload. "
                    "The agent will also run its own extraction from the PDF bytes."
    )
    user_tone: str = Field(default="professional", description="Writing tone preference")


class AgentRunResponse(BaseModel):
    """
    Result FastAPI returns to Django after the agent completes.

    Django uses this to update the Application and create an AgentRun record.
    The `status` field drives the Application.status update.
    """
    run_id: str
    application_id: str
    status: str = Field(description="completed | failed | partial")

    # Phase 2 outputs (populated now)
    jd_parsed: Optional[dict] = None
    resume_parsed: Optional[dict] = None

    # Phase 4–9 outputs (None until those phases are built)
    skill_alignment: Optional[dict] = None
    resume_rewritten: Optional[dict] = None
    cover_letter_content: Optional[str] = None
    cold_email_variants: Optional[list] = None

    # Observability
    steps_completed: List[str] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)
    duration_ms: int = 0
